# Railway deployment configuration

# Build configuration
build:
  builder: "nixpacks"
  buildCommand: "pip install -r requirements.txt"

# Runtime configuration
runtime:
  command: "uvicorn main:app --host 0.0.0.0 --port $PORT"
  healthcheckPath: "/health"
  healthcheckTimeout: 30

# Environment variables (set these in Railway dashboard)
# Required:
# - CEREBRAS_API_KEY: Your Cerebras API key
# - WORDPRESS_URL: Your WordPress site URL
# - WORDPRESS_USERNAME: WordPress username
# - WORDPRESS_PASSWORD: WordPress application password
# - WORDPRESS_API_URL: WordPress REST API URL

# Optional:
# - QDRANT_URL: Qdrant URL (default: http://localhost:6333)
# - QDRANT_API_KEY: Qdrant API key (if using cloud)
# - QDRANT_COLLECTION_NAME: Collection name (default: wordpress_content)
# - CEREBRAS_API_BASE: Cerebras API base URL
# - CEREBRAS_MODEL: Cerebras model name
# - MAX_SEARCH_RESULTS: Max results per search
# - SEARCH_TIMEOUT: Search timeout in seconds
# - EMBEDDING_DIMENSION: Embedding vector dimension

# Scaling
scaling:
  minInstances: 1
  maxInstances: 3

# Resources
resources:
  cpu: "1"
  memory: "1Gi"

# Networking
networking:
  port: 8000
  protocol: "http"

# Health checks
healthChecks:
  - path: "/health"
    interval: 30
    timeout: 10
    retries: 3
